// Generated by tools/art/fxatlas.py — do not edit by hand.
using Godot;

namespace LastTide;

/// <summary>UV rects (normalised) and pixel sizes of the sprites packed in fx/fx.png.</summary>
public static class FxAtlas
{
    public static readonly Rect2 Barrel = new(0.460938f, 0.730469f, 0.125000f, 0.175781f);
    public static readonly Vector2 BarrelPx = new(128, 90);
    public static readonly Rect2 BarrelEnd = new(0.199219f, 0.398438f, 0.124023f, 0.250000f);
    public static readonly Vector2 BarrelEndPx = new(127, 128);
    public static readonly Rect2 Chest = new(0.591797f, 0.730469f, 0.125000f, 0.175781f);
    public static readonly Vector2 ChestPx = new(128, 90);
    public static readonly Rect2 Crate = new(0.199219f, 0.730469f, 0.125000f, 0.242188f);
    public static readonly Vector2 CratePx = new(128, 124);
    public static readonly Rect2 Grating = new(0.455078f, 0.398438f, 0.125000f, 0.250000f);
    public static readonly Vector2 GratingPx = new(128, 128);
    public static readonly Rect2 Hat = new(0.585938f, 0.398438f, 0.119141f, 0.250000f);
    public static readonly Vector2 HatPx = new(122, 128);
    public static readonly Rect2 Plank = new(0.853516f, 0.730469f, 0.125000f, 0.091797f);
    public static readonly Vector2 PlankPx = new(128, 47);
    public static readonly Rect2 Plank2 = new(0.722656f, 0.730469f, 0.125000f, 0.154297f);
    public static readonly Vector2 Plank2Px = new(128, 79);
    public static readonly Rect2 Rope = new(0.329102f, 0.398438f, 0.120117f, 0.250000f);
    public static readonly Vector2 RopePx = new(123, 128);
    public static readonly Rect2 Smoke0 = new(0.382812f, 0.011719f, 0.187500f, 0.371094f);
    public static readonly Vector2 Smoke0Px = new(192, 190);
    public static readonly Rect2 Smoke1 = new(0.710938f, 0.398438f, 0.187500f, 0.246094f);
    public static readonly Vector2 Smoke1Px = new(192, 126);
    public static readonly Rect2 Smoke2 = new(0.576172f, 0.011719f, 0.187500f, 0.371094f);
    public static readonly Vector2 Smoke2Px = new(192, 190);
    public static readonly Rect2 Smoke3 = new(0.005859f, 0.398438f, 0.187500f, 0.320312f);
    public static readonly Vector2 Smoke3Px = new(192, 164);
    public static readonly Rect2 Smoke4 = new(0.005859f, 0.730469f, 0.187500f, 0.242188f);
    public static readonly Vector2 Smoke4Px = new(192, 124);
    public static readonly Rect2 Smoke5 = new(0.769531f, 0.011719f, 0.187500f, 0.355469f);
    public static readonly Vector2 Smoke5Px = new(192, 182);
    public static readonly Rect2 Smoke6 = new(0.005859f, 0.011719f, 0.183594f, 0.375000f);
    public static readonly Vector2 Smoke6Px = new(188, 192);
    public static readonly Rect2 Smoke7 = new(0.195312f, 0.011719f, 0.181641f, 0.375000f);
    public static readonly Vector2 Smoke7Px = new(186, 192);
    public static readonly Rect2 Spar = new(0.330078f, 0.730469f, 0.125000f, 0.203125f);
    public static readonly Vector2 SparPx = new(128, 104);
}
