// Generated by tools/art/atlas.py — do not edit by hand. Regions (px) of the world-art atlases.
using Godot;

namespace LastTide;

public static partial class WorldArt
{
    public static readonly Vector2 LandSize = new(1024, 1024);
    public static readonly Dictionary<string, Rect2> Land = new()
    {
        ["altar"] = new Rect2(520, 513, 160, 112),
        ["arch"] = new Rect2(690, 350, 160, 130),
        ["bent-tree"] = new Rect2(180, 513, 160, 118),
        ["colonnade"] = new Rect2(736, 180, 160, 156),
        ["column"] = new Rect2(10, 10, 121, 160),
        ["conifer"] = new Rect2(141, 10, 106, 160),
        ["conifers"] = new Rect2(396, 180, 160, 159),
        ["crag"] = new Rect2(10, 651, 160, 106),
        ["dead-tree"] = new Rect2(257, 10, 141, 160),
        ["dune"] = new Rect2(350, 861, 160, 48),
        ["fallen-columns"] = new Rect2(10, 861, 160, 65),
        ["fern"] = new Rect2(350, 350, 160, 144),
        ["heather"] = new Rect2(10, 767, 160, 84),
        ["hill"] = new Rect2(180, 861, 160, 54),
        ["jungle"] = new Rect2(690, 513, 160, 109),
        ["jungle-tree"] = new Rect2(408, 10, 159, 160),
        ["knoll"] = new Rect2(690, 767, 160, 71),
        ["lava-rocks"] = new Rect2(520, 651, 160, 91),
        ["mangrove"] = new Rect2(566, 180, 160, 159),
        ["mangroves"] = new Rect2(520, 350, 160, 134),
        ["obelisk"] = new Rect2(577, 10, 101, 160),
        ["palm"] = new Rect2(10, 180, 103, 160),
        ["palm-lean"] = new Rect2(688, 10, 139, 160),
        ["palm-pair"] = new Rect2(837, 10, 132, 160),
        ["peaks"] = new Rect2(520, 767, 160, 72),
        ["reeds"] = new Rect2(180, 350, 160, 149),
        ["rocks"] = new Rect2(690, 651, 160, 86),
        ["ruin-tower"] = new Rect2(10, 513, 160, 128),
        ["ruined-wall"] = new Rect2(350, 513, 160, 114),
        ["sea-stack"] = new Rect2(10, 350, 160, 153),
        ["slate-rocks"] = new Rect2(350, 767, 160, 79),
        ["smoke"] = new Rect2(123, 180, 130, 160),
        ["statue"] = new Rect2(263, 180, 123, 160),
        ["stone-head"] = new Rect2(180, 651, 160, 102),
        ["tuft"] = new Rect2(180, 767, 160, 82),
        ["volcano"] = new Rect2(350, 651, 160, 98),
    };
    public static readonly Vector2 PortsSize = new(1024, 512);
    public static readonly Dictionary<string, Rect2> Ports = new()
    {
        ["barrels"] = new Rect2(650, 170, 150, 123),
        ["church"] = new Rect2(10, 10, 114, 150),
        ["customs-house"] = new Rect2(170, 170, 150, 134),
        ["house"] = new Rect2(490, 170, 150, 131),
        ["jetty"] = new Rect2(134, 10, 49, 150),
        ["lantern"] = new Rect2(193, 10, 84, 150),
        ["lighthouse"] = new Rect2(287, 10, 75, 150),
        ["row"] = new Rect2(170, 319, 150, 106),
        ["sea-cave"] = new Rect2(330, 170, 150, 132),
        ["shack"] = new Rect2(10, 319, 150, 107),
        ["star-fort"] = new Rect2(845, 10, 150, 149),
        ["stilt-hut"] = new Rect2(10, 170, 150, 139),
        ["stilt-huts"] = new Rect2(810, 170, 150, 122),
        ["tower"] = new Rect2(372, 10, 144, 150),
        ["townhouse"] = new Rect2(526, 10, 97, 150),
        ["warehouse"] = new Rect2(330, 319, 150, 100),
        ["watchtower"] = new Rect2(633, 10, 88, 150),
        ["windmill"] = new Rect2(731, 10, 104, 150),
    };
    public static readonly Vector2 LifeSize = new(1024, 512);
    public static readonly Dictionary<string, Rect2> Life = new()
    {
        ["dolphin"] = new Rect2(649, 10, 160, 125),
        ["fish"] = new Rect2(10, 10, 149, 160),
        ["gull-flap"] = new Rect2(169, 10, 158, 160),
        ["gull-glide"] = new Rect2(819, 10, 160, 118),
        ["gull-spread"] = new Rect2(180, 180, 160, 75),
        ["spout"] = new Rect2(337, 10, 132, 160),
        ["weed"] = new Rect2(479, 10, 160, 129),
        ["whale-back"] = new Rect2(350, 180, 160, 61),
        ["whale-tail"] = new Rect2(10, 180, 160, 109),
    };
    public static readonly Vector2 DecorSize = new(1024, 512);
    public static readonly Dictionary<string, Rect2> Decor = new()
    {
        ["rose"] = new Rect2(10, 10, 480, 478),
    };
}
