# uv run -q --with pillow python tools/art/atlas.py game/WorldArt.cs <set>=<dir>:<max-px> [...]
# Packs every PNG in each <dir> into assets/art/<set>/atlas.png (shelf packing, 10 px transparent gutters so mipmaps
# never bleed between items) and writes one C# table of the regions: WorldArt.<Set>["name"] = Rect2(x, y, w, h).
import os, sys, glob
from PIL import Image

cs_out = sys.argv[1]
entries = []
for spec in sys.argv[2:]:
    name, rest = spec.split('=', 1)
    src, mx = rest.rsplit(':', 1)
    mx = int(mx)
    items = []
    for f in sorted(glob.glob(os.path.join(src, '*.png'))):
        im = Image.open(f).convert('RGBA')
        s = min(1.0, mx / max(im.size))
        if s < 1.0:
            im = im.resize((max(1, round(im.width * s)), max(1, round(im.height * s))), Image.LANCZOS)
        items.append((os.path.splitext(os.path.basename(f))[0], im))
    items.sort(key=lambda t: -t[1].height)
    W, pad = 1024, 10
    x = y = pad; row_h = 0; rects = {}
    for key, im in items:
        if x + im.width + pad > W:
            x = pad; y += row_h + pad; row_h = 0
        rects[key] = (x, y, im.width, im.height)
        x += im.width + pad; row_h = max(row_h, im.height)
    H = y + row_h + pad
    H = 1 << (H - 1).bit_length()   # power of two keeps every mip level exact
    atlas = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    for key, im in items:
        atlas.paste(im, rects[key][:2])
    out = f'assets/art/{name}/atlas.png'
    os.makedirs(os.path.dirname(out), exist_ok=True)
    atlas.save(out, optimize=True)
    print(f'{out}: {W}x{H}, {len(items)} items, {os.path.getsize(out) // 1024} KB')
    entries.append((name, rects, (W, H)))

with open(cs_out, 'w') as f:
    f.write('// Generated by tools/art/atlas.py — do not edit by hand. Regions (px) of the world-art atlases.\n')
    f.write('using Godot;\n\nnamespace LastTide;\n\npublic static partial class WorldArt\n{\n')
    for name, rects, size in entries:
        field = name[0].upper() + name[1:]
        f.write(f'    public static readonly Vector2 {field}Size = new({size[0]}, {size[1]});\n')
        f.write(f'    public static readonly Dictionary<string, Rect2> {field} = new()\n    {{\n')
        for key in sorted(rects):
            x, y, w, h = rects[key]
            f.write(f'        ["{key}"] = new Rect2({x}, {y}, {w}, {h}),\n')
        f.write('    };\n')
    f.write('}\n')
print('wrote', cs_out)
