# uv run -q --with pillow python tools/art/fxatlas.py <atlas.png> <table.cs> <ClassName> <width> name=path ...
# Packs sprites into one atlas (shelf packing, 4 px gutters with edge padding so mipmaps don't bleed) and writes a
# C# table of normalised UV rects and pixel sizes, so a whole particle system draws with one texture = one call.
import sys
from PIL import Image
out, cs, cls, W = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])
items = [(a.split('=')[0], Image.open(a.split('=')[1]).convert('RGBA')) for a in sys.argv[5:]]
items.sort(key=lambda t: -t[1].height)
G = 6
x = y = G; shelf = 0; place = []
for name, im in items:
    if x + im.width + G > W:
        x = G; y += shelf + G; shelf = 0
    place.append((name, im, x, y)); x += im.width + G; shelf = max(shelf, im.height)
H = y + shelf + G
H2 = 1
while H2 < H: H2 *= 2
atlas = Image.new('RGBA', (W, H2), (0, 0, 0, 0))
for name, im, px, py in place:
    atlas.paste(im, (px, py))
atlas.save(out, optimize=True)
lines = [f'// Generated by tools/art/fxatlas.py — do not edit by hand.', 'using Godot;', '', 'namespace LastTide;', '',
         f'/// <summary>UV rects (normalised) and pixel sizes of the sprites packed in {out.split("assets/art/")[-1]}.</summary>',
         f'public static class {cls}', '{']
for name, im, px, py in sorted(place):
    ident = ''.join(p.capitalize() for p in name.replace('-', '_').split('_'))
    lines.append(f'    public static readonly Rect2 {ident} = new({px / W:.6f}f, {py / H2:.6f}f, {im.width / W:.6f}f, {im.height / H2:.6f}f);')
    lines.append(f'    public static readonly Vector2 {ident}Px = new({im.width}, {im.height});')
lines.append('}')
open(cs, 'w').write('\n'.join(lines) + '\n')
print(out, (W, H2), len(place))
